### ISSUE TITLE
How to change the font-size

### ISSUE THREAD

**Issue by AnovaF** [stla/shinyDatetimePickers#18]
Hello, I am using datetimeMaterialPickerInput in my Shiny app.
Unfortunately the font-size is too large. Is there a way to control the font-size?

I attach a reprex:
[Reprex shinyDatetimePickers.txt](https://github.com/stla/shinyDatetimePickers/files/14185895/Reprex.shinyDatetimePickers.txt)

This is the appearence in the browser:
![Reprex shinyDatetimePickers](https://github.com/stla/shinyDatetimePickers/assets/44157022/7fbd1064-c985-4455-ab1d-03ec4c475c2e)

The problem is the bs_theme that I use. Without this theme the font-size is good.

Thanks very much for your help, Gerben

**Comment by stla** [comment]
Hello,
Try to include this CSS:
```css
.MuiInputBase-input {
  font-size: 12px;
}
```

**Comment by AnovaF** [comment]
Hi, I added this CSS but unfortunately it does not change the font-size. It remains too large.

**Comment by stla** [comment]
Someone else told me that this works. How did you include this CSS?

**Comment by AnovaF** [comment]
Hi Stia, I placed it in the head of my webpage and I used the style parameter of the function datetimeMaterialPickerInput.
I attach the 2 R program files. I have to upload these as .txt files, you can rename these to .R and then run the code in R or RStudio. Made the font-size 6 px, but nothing changes in the appearance as given above.

[Reprex shinyDatetimePickers - v1.txt](https://github.com/stla/shinyDatetimePickers/files/14206228/Reprex.shinyDatetimePickers.-.v1.txt)

[Reprex shinyDatetimePickers - v2.txt](https://github.com/stla/shinyDatetimePickers/files/14206229/Reprex.shinyDatetimePickers.-.v2.txt)

**Comment by stla** [comment]
Indeed. It works like this:
```css
.MuiInputBase-input {
  font-size: 12px !important;
}
```

**Comment by AnovaF** [comment]
Yes, that works, but only partly. The output of my Shiny now looks like shown below. How can I change the font of the label and the font of all text element of the calander that pops up?

![Reprex shinyDatetimePickers - mod_1](https://github.com/stla/shinyDatetimePickers/assets/44157022/8e24f3e6-775a-47a0-bc5e-d50dfb36c3fa)

**Comment by stla** [comment]
You have to learn how to use the inspector tools of your browser. Right-click on an element and the inspector tools will reveal the CSS properties of this element. For example, for the label it is:
```css
.datetimeMaterialPicker .MuiFormLabel-root {

}
```

**Comment by stla** [comment]
I checked. All the font sizes of the texts inside the calendar are expressed in [rem units](https://www.sitepoint.com/understanding-and-using-rem-units-in-css/). That means you just have to set the `font-size` property of the `html` element to control all the font sizes of the texts inside the calendar: they are relative to the font size of `html`.
```css
html {
  font-size: 8px;
}
```

**Comment by AnovaF** [comment]
Thanks very much for your suggestions, Stia. 
Learned some new HTML/CSS tricks.
